;
; This file is provided as part of the callbricks Asterisk workbench pkg
; It is not a generated file so you may freely change it but it WILL be  
; overwritten if/when you upgrade callbricks so please make a copy if you
; wish to preserve your changes across an upgrade
;
[callbricks_hosted_user]
type=user
music_on_hold_when_empty=yes  
music_on_hold_class=default   
announce_join_leave=yes 

[callbricks_user]
type=user
music_on_hold_when_empty=yes  
music_on_hold_class=default  
