[Breeders]
context=Breederspark
parkext=700
parkpos=701-703

[H2S]
context=H2Spark
parkext=700
parkpos=701-703

[Rearing]
context=Rearingpark
parkext=700
parkpos=701-703

[Turkeys]
context=Turkeyspark
parkext=700
parkpos=701-703

[default]
context=defaultpark
parkext=700
parkpos=701-703

