#!/bin/bash
[ ! -e /opt/sark/db/sark.db ] && exit 4

/usr/bin/logger Regenerating Asterisk

php /opt/gcs/generator/runApacheGen.php

# copy the DB
/bin/cp /opt/sark/db/sark.db /opt/sark/db/sark.copy.db
/bin/mv /opt/sark/db/sark.copy.db /opt/sark/db/sark.rdonly.db
#
/usr/bin/logger Regenerating Asterisk Finished
#/usr/bin/sqlite3 /opt/gcs/db/sqlite.db "UPDATE globals SET MYCOMMIT='NO' WHERE pkey='global';"
